### ISSUE TITLE
Now It's not saving...

### ISSUE THREAD

**Issue by CounterGambit** [jrg94/color-picker#8]
All that trouble it took to get the package to work (and it was a complete reinstall of python that fixed that issue), and now it won't save the file.

I follow the steps as written;

Name: NWGMain
Color: 33,64,154

It works, showing me where I need to put the slider, and the selector. Except, It's not saving the file anywhere. I've gone looking, thinking it might be in some random folder. I've searched using the computer's search function, and nothing.

Simple question, because I'm sure this is a P.I.C.N.I.C. ("Problem In Chair, Not In Computer," for those who don't know what I mean by picnic) issue: What could I possibly be doing wrong?

**Comment by jrg94** [comment]
Good question! As long as there aren't any errors, I would suspect the file is saving wherever you are running the script. If you're in windows, you can run a quick `dir` to check. Otherwise, `ls` should work. 

Alternatively, you can try providing an entire path on the first line:

```shell
name: /path/to/file/NWGMain.png
```

That way, you'll know exactly where the file should go.

**Comment by CounterGambit** [comment]
including the path for the file to be saved in worked. Thanks.
